version: '3.8'

services:

  backend:
    build:
      dockerfile: Dockerfile
      context: "./backend"
    # volumes:
    #   - /app/node_modules
    #   - ./backend:/app
    ports:
      - "5000:5000"
    expose:
      - "5000"
    environment: 
      - CHOKIDAR_USEPOLLING=true
  
  frontend:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./frontend
    # volumes:
    #   - /app/node_modules
    #   - ./frontend:/app
    ports:
      - "3000:3000"
    expose:
      - "3000"
    environment: 
      - CHOKIDAR_USEPOLLING=true